name: sushi-zeta
networks:
- id: 7000
  start_block: 0
  contracts:
  - name: UniswapV3Factory
    address:
    - 0xB45e53277a7e0F1D35f2a77160e91e25507f1763
    handler: src/EventHandlers.ts
    events:
    - event: PoolCreated(address indexed token0, address indexed token1, uint24 indexed fee, int24 tickSpacing, address pool)
  - name: UniswapV3Pool
    address:
    - 0xB45e53277a7e0F1D35f2a77160e91e25507f1763
    handler: src/EventHandlers.ts
    events:
    - event: Swap(address indexed sender, address indexed recipient, int256 amount0, int256 amount1, uint160 sqrtPriceX96, uint128 liquidity, int24 tick)
